POST http://localhost:3333/events
Content-Type: application/json

{
  "title":123,
  "details":null,
  "maximumAttendees":1
}
// 667dabd0-ac85-4c15-b0c9-22ac0decb89e"
###
POST http://localhost:3333/events/667dabd0-ac85-4c15-b0c9-22ac0decb89e/attendees
Content-Type: application/json

{
  "name":"teste",
  "email":"teste@a.com.br"
}

###
POST http://localhost:3333/events/3c98202f-4c38-47c7-ab7b-72eb8c75f224/attendees
Content-Type: application/json

{
  "name":"teste",
  "email":"teste@az.com.br"
}

###
GET http://localhost:3333/events/3c98202f-4c38-47c7-ab7b-72eb8c75f224

###
GET http://localhost:3333/attendees/4/badge

###
GET http://localhost:3333/attendees/8/check-in

###
GET http://localhost:3333/events/667dabd0-ac85-4c15-b0c9-22ac0decb89e/attendees

###
// consulta com query
GET http://localhost:3333/events/667dabd0-ac85-4c15-b0c9-22ac0decb89e/attendees?query=teste